#Minecraft server properties
motd=ShenPulse SandBox 3
server-port=25565
query.port=25565
rcon.port=25575
level-name=shenpulse-sandbox-3
level-seed=
level-type=minecraft\:normal
generator-settings={}
gamemode=creative
difficulty=easy
max-players=20
online-mode=false
enforce-secure-profile=true
white-list=false
spawn-protection=0
enable-command-block=false
allow-flight=true
pvp=true
spawn-npcs=true
spawn-animals=true
spawn-monsters=true
hardcore=false
view-distance=10
simulation-distance=10
enable-rcon=false
enable-query=false
enable-status=true
allow-nether=true
force-gamemode=true
generate-structures=true
hide-online-players=false
network-compression-threshold=256
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
rate-limit=0
require-resource-pack=false
sync-chunk-writes=true
use-native-transport=true
max-tick-time=60000
max-world-size=29999984
entity-broadcast-range-percentage=100
broadcast-console-to-ops=false
broadcast-rcon-to-ops=false
function-permission-level=2
debug=false
accepts-transfers=false
